server:
  port: 8084
## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://10.1.254.12:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root123456
    driver-class-name: com.mysql.jdbc.Driver
## Redis 配置
  redis:
    cluster:
      nodes:
        - 10.1.254.12:7000
        - 10.1.254.12:7001
        - 10.1.254.12:7002
        - 10.1.254.13:7003
        - 10.1.254.13:7004
        - 10.1.254.13:7005